-- DonDude schema.
--
-- The database is the single source of truth for the fleet: there is no config
-- file. Everything an operator can change lives here and is edited through the
-- web UI.
--
-- Secrets (router passwords, key passphrases, the GitHub token) are stored
-- sealed by the application with ChaCha20-Poly1305 under `DONDUDE_MASTER_KEY`.
-- A dump of this database therefore leaks no credentials on its own.
--
-- UUIDs are generated by the application, so no `pgcrypto` and no superuser is
-- needed to install this schema.

-- ---------------------------------------------------------------------------
-- Operators
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id            UUID PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    -- Argon2id PHC string; the parameters travel with the hash.
    password_hash TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ
);

-- Only the SHA-256 of a session cookie is stored, so a database leak cannot be
-- replayed as a live session.
CREATE TABLE sessions (
    token_hash TEXT PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    user_agent TEXT
);

CREATE INDEX sessions_expiry_idx ON sessions (expires_at);

-- ---------------------------------------------------------------------------
-- Fleet
-- ---------------------------------------------------------------------------

CREATE TABLE tenants (
    id         UUID PRIMARY KEY,
    slug       TEXT NOT NULL UNIQUE,
    name       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE devices (
    id               UUID PRIMARY KEY,
    tenant_id        UUID NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    name             TEXT NOT NULL,
    host             TEXT NOT NULL,
    port             INTEGER NOT NULL DEFAULT 22 CHECK (port BETWEEN 1 AND 65535),
    username         TEXT NOT NULL,
    auth_kind        TEXT NOT NULL CHECK (auth_kind IN ('password', 'key', 'agent')),
    -- Sealed password (auth_kind='password') or key passphrase (auth_kind='key').
    secret_sealed    TEXT,
    private_key_path TEXT,
    tags             TEXT[] NOT NULL DEFAULT '{}',
    enabled          BOOLEAN NOT NULL DEFAULT true,

    -- Last observed, for display only; the device is the source of truth.
    identity         TEXT,
    firmware         TEXT,
    model            TEXT,
    serial           TEXT,
    last_seen_at     TIMESTAMPTZ,
    last_outcome     TEXT,
    last_detail      TEXT,

    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name),

    -- A device that authenticates by password must actually have one stored.
    CONSTRAINT device_password_needs_secret
        CHECK (auth_kind <> 'password' OR secret_sealed IS NOT NULL),
    CONSTRAINT device_key_needs_path
        CHECK (auth_kind <> 'key' OR private_key_path IS NOT NULL)
);

CREATE INDEX devices_tenant_idx ON devices (tenant_id);

-- ---------------------------------------------------------------------------
-- Settings (single row)
-- ---------------------------------------------------------------------------

-- `repo_path` deliberately absent: where the backup working tree lives is a
-- deployment concern (a mounted volume), not something to change from a browser.
CREATE TABLE settings (
    id                   BOOLEAN PRIMARY KEY DEFAULT true CHECK (id),
    path_template        TEXT NOT NULL DEFAULT '{tenant}/{device}.rsc',
    committer_name       TEXT NOT NULL DEFAULT 'DonDude',
    committer_email      TEXT NOT NULL DEFAULT 'dondude@localhost',

    remote_url           TEXT,
    remote_branch        TEXT NOT NULL DEFAULT 'main',
    remote_push          BOOLEAN NOT NULL DEFAULT true,
    git_username         TEXT NOT NULL DEFAULT 'x-access-token',
    git_token_sealed     TEXT,

    export_mode          TEXT NOT NULL DEFAULT 'terse'
                             CHECK (export_mode IN ('compact', 'terse', 'verbose')),
    show_sensitive       BOOLEAN NOT NULL DEFAULT false,

    concurrency          INTEGER NOT NULL DEFAULT 8 CHECK (concurrency BETWEEN 1 AND 256),
    connect_timeout_secs INTEGER NOT NULL DEFAULT 10 CHECK (connect_timeout_secs > 0),
    command_timeout_secs INTEGER NOT NULL DEFAULT 120 CHECK (command_timeout_secs > 0),
    host_key_policy      TEXT NOT NULL DEFAULT 'accept-new'
                             CHECK (host_key_policy IN ('strict', 'accept-new', 'off')),

    schedule_enabled     BOOLEAN NOT NULL DEFAULT false,
    schedule_hour        INTEGER NOT NULL DEFAULT 2 CHECK (schedule_hour BETWEEN 0 AND 23),
    schedule_minute      INTEGER NOT NULL DEFAULT 30 CHECK (schedule_minute BETWEEN 0 AND 59),

    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO settings (id) VALUES (true);

-- ---------------------------------------------------------------------------
-- Run history
-- ---------------------------------------------------------------------------

CREATE TABLE backup_runs (
    id          UUID PRIMARY KEY,
    started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    status      TEXT NOT NULL DEFAULT 'running'
                    CHECK (status IN ('running', 'completed', 'failed')),
    trigger     TEXT NOT NULL CHECK (trigger IN ('manual', 'schedule', 'cli')),
    changed     INTEGER NOT NULL DEFAULT 0,
    unchanged   INTEGER NOT NULL DEFAULT 0,
    failed      INTEGER NOT NULL DEFAULT 0,
    dry_run     BOOLEAN NOT NULL DEFAULT false,
    pushed      BOOLEAN NOT NULL DEFAULT false,
    push_detail TEXT,
    -- Progress log, persisted when the run ends.
    log         TEXT NOT NULL DEFAULT ''
);

CREATE INDEX backup_runs_started_idx ON backup_runs (started_at DESC);

-- One row per device per run: the audit trail that answers "when did this
-- router last change, and did we manage to record it?".
CREATE TABLE backup_events (
    id         UUID PRIMARY KEY,
    run_id     UUID NOT NULL REFERENCES backup_runs (id) ON DELETE CASCADE,
    tenant_id  UUID NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    device_id  UUID NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
    outcome    TEXT NOT NULL
                   CHECK (outcome IN ('unchanged', 'committed', 'would_change', 'failed')),
    commit_id  TEXT,
    repo_path  TEXT NOT NULL,
    insertions INTEGER NOT NULL DEFAULT 0,
    deletions  INTEGER NOT NULL DEFAULT 0,
    firmware   TEXT,
    detail     TEXT,
    elapsed_ms BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX backup_events_device_created_idx ON backup_events (device_id, created_at DESC);
CREATE INDEX backup_events_run_idx ON backup_events (run_id);

-- ---------------------------------------------------------------------------
-- Tenant isolation
-- ---------------------------------------------------------------------------
--
-- Enforced in PostgreSQL rather than in application filtering, keyed on the
-- transaction-local `dondude.tenant_id` setting. Note that PostgreSQL exempts a
-- table's OWNER from RLS unless the table is put in FORCE mode: run the
-- application as a role that does not own these tables for the policies to bite.

ALTER TABLE devices       ENABLE ROW LEVEL SECURITY;
ALTER TABLE backup_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON devices
    USING (tenant_id = current_setting('dondude.tenant_id', true)::UUID);

CREATE POLICY tenant_isolation ON backup_events
    USING (tenant_id = current_setting('dondude.tenant_id', true)::UUID);
